### ISSUE TITLE
Re-compute polarized DIS predictions with fixed Yadism and EKO

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/yadism#291]
We need to re-compute all the Polarized DIS FK table predictions making sure that:

- [x] the grids include the updated type of initial state for the metadata
- [x] they are generated with the fixed version of EKOs
- [x] we no longer rely on the k-factors to compute $g_1$ and the asymmetries (because of improvements in `n3fit`) 

These predictions include all the combinations of ZM and FONLL for the perturbative orders NLO and NNLO.
```[tasklist]
### Tasks
- [ ] https://github.com/NNPDF/yadism/pull/289
- [ ] https://github.com/NNPDF/yadism/pull/232
- [ ] https://github.com/NNPDF/nnpdf/pull/2122
- [ ] https://github.com/NNPDF/pinecards/pull/181
```

**Comment by giacomomagni** [comment]
The various tasks have been addressed in the corresponding PRs
